version: '3.9'

services:
  ctagi:
    container_name: ibl
    image: jupyter/datascience-notebook
    #ports:
    #  - '8090:8090'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/inductive-bias-learning/:/home/inductive-bias-learning/
    command: start-notebook.sh --NotebookApp.token=''